import { useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'

export default function Register() {
  const { inscription, erreur } = useAuth(); const naviguer = useNavigate(); const [email, definirEmail] = useState(''); const [motDePasse, definirMotDePasse] = useState(''); const [confirmation, definirConfirmation] = useState(''); const [message, definirMessage] = useState<string | null>(null); const [envoi, definirEnvoi] = useState(false)
  const soumettre = async (evenement: FormEvent) => { evenement.preventDefault(); if (motDePasse !== confirmation) { definirMessage('Les mots de passe ne correspondent pas.'); return }; definirMessage(null); definirEnvoi(true); try { await inscription(email, motDePasse); naviguer('/') } catch { definirMessage('Impossible de créer le compte pour le moment.') } finally { definirEnvoi(false) } }
  return <section className="auth-page"><div className="auth-intro"><span className="surtitre">REJOINDRE CHIPSUI</span><h1>Construisez votre coin croustillant.</h1><p>Gardez une trace des saveurs que vous aimez et de celles qu'il vous reste à croquer.</p></div><form className="formulaire" onSubmit={soumettre}><span className="surtitre">INSCRIPTION</span><h2>Créer un compte</h2><label>Email<input type="email" value={email} onChange={e => definirEmail(e.target.value)} required /></label><label>Mot de passe<input type="password" minLength={6} value={motDePasse} onChange={e => definirMotDePasse(e.target.value)} required /></label><label>Confirmer<input type="password" value={confirmation} onChange={e => definirConfirmation(e.target.value)} required /></label>{(message || erreur) && <p className="message-erreur">{message || erreur}</p>}<button className="bouton bouton-primaire bouton-large" disabled={envoi}>{envoi ? 'Création...' : 'Créer mon compte'}</button><p className="aide-formulaire">Déjà inscrit ? <Link to="/login">Se connecter</Link></p></form></section>
}
